name: Daily Frontend Jobs Scraper

on:
  schedule:
    # Runs every day at 7 PM IST (13:30 UTC)
    - cron: "30 13 * * *"
  workflow_dispatch:  # allow manual run from Actions tab

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Debug - Show package.json
        run: cat package.json

      - name: Run job scraper
        run: node job_scrapper.js
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
